### ISSUE TITLE
请问在我的博客上插件为什么不能正常显示？

### ISSUE THREAD

**Issue by vinouno** [PPLong222/hexo-leetcode-calendar#2]
- 问题复现页面地址：https://vinouno.github.io/posts/d87f7e0c/
- 所使用的版本：0.4.0，当前版本
- 问题描述：完全按照readme.md安装，并在一篇post中使用指定格式引用插件，但是插件不能正常显示（可以看点击我的链接复现问题）。
- 可能的原因：

开发者模式控制台报错：
```
Uncaught SyntaxError: Expected property name or '}' in JSON at position 1
    at JSON.parse (<anonymous>)
    at leetcodeCalendar (（索引）:489:28)
    at （索引）:685:3
```
不知道是否与此问题有关。
- 为解决问题所作的努力：
检查了配置,完全按照readme所写。
```
leetcodecalendar:
enable: true
submitGap: 5
showIcon: true
color:
  submitColor: '#c4c6c9'
  bgColor: '#252d38'
  subColors: ['#ebedf0', '#bef5cb', '#85e89d', '#34d058', '#1c992f']
```
post内容：
```
---
title: test
description: <div align="center"> </div>
abbrlink: d87f7e0c
date: 2023-02-11 11:23:01
tags:
categories:
---
{% leetcode "vicvino" %}
```

恳请您的解答。
